- label: LinkedIn
  href: https://linkedin.com/in/tmthyng
  icon: linkedin
- label: read.cv
  href: https://read.cv/timothyng
  icon: file-earmark-pdf
- label: Email me
  href: mailto:contact.tim.ng@gmail.com
  icon: chat-left-text
